### ISSUE TITLE
Morning session pear to pear code review

### ISSUE THREAD

**Issue by HERMON-1995** [yodit93/Todo-list-app#6]
# Hi @[yodit93](https://github.com/yodit93),🙋‍♀️

Good job so far! 👏

Highlights!

•	Good code organization and working app ✔️
•	Descriptive README ✔️
•	All linters passing ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- Please keep your merged branches intact for clear development history. 👍 
- Kindly add a link to the live demo in the readme file from the dist folder. 😊

## Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@HERMON-1995`  if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

<hr>
 
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

<hr>

**Comment by yodit93** [comment]
Thank you.
